import Background from '@/components/Background'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import ScrollContainer from '@/components/ScrollContainer'
import Clients from '@/sections/Clients'
import HomeContact from '@/sections/Contact'
import Featured from '@/sections/Featured'
import Hero from '@/sections/Hero'
import { LoaderScreen } from '@/utilities'
import Head from 'next/head'
import Script from 'next/script'

export default function Home() {
  return (
    <>
      <Head>
        <title>OkayDone | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js" crossOrigin='anonymous' defer></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js" crossOrigin='anonymous' defer></script>
        <script type='text/javascript' src="/scripts/script.js" defer></script>
      </Head>
      <LoaderScreen />
      <main className={"main"}>
        <Background />
        <Navigation />
        <ScrollContainer>
        <Hero />
        <Clients />
        <Featured />
        <HomeContact />
        <Footer />
        </ScrollContainer>
      </main>
    </>
  )
}
