import Background from '@/components/Background'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import ScrollContainer from '@/components/ScrollContainer'
import { fetchClients } from '@/controller/Content'
import Clients from '@/sections/Clients'
import HomeContact from '@/sections/Contact'
import Hero from '@/sections/Hero'
import Head from 'next/head'

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>OkayDone | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <Background />
        <Navigation />
        <ScrollContainer>
        <Hero />
        <Clients clients={data && data.clients} />
        <HomeContact />
        <Footer />
        </ScrollContainer>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const res = await fetchClients()
  return { props: { data: res }}
}
