import Background from '@/components/Background'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import ScrollContainer from '@/components/ScrollContainer'
import { fetchClients } from '@/controller/Content'
import HomeContact from '@/sections/Contact'
import Head from 'next/head'
import { AnimatePresence, motion } from 'framer-motion'
import { useRouter } from 'next/router'
import Link from 'next/link'

export default function Work({data}) {
  const router = useRouter()
  const {filter} = router.query
  return (
    <>
      <Head>
        <title>OkayDone | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <Background />
        <Navigation />
        <ScrollContainer>
          <div className="work-hero">
            <div className="container">
              <div className="work-hero-header">
                <h1>discover our</h1>
                <h1>latest work</h1>
              </div>
            </div>
          </div>
         <div className="container">
          <ul className="work-filter-list">
              <motion.li
              key={"filter1"}
              initial={{y: 50, opacity: 0}}
              animate={{y: 0, opacity: 1}}
              transition={{type: 'spring', bounce: 0.4, delay: 0.5}}
              >
                <Link className={!filter ? "active" : ""} href={"/work"}>All</Link>
              </motion.li>
              <motion.li
              key={"filter2"}
              initial={{y: 50, opacity: 0}}
              animate={{y: 0, opacity: 1}}
              transition={{type: 'spring', bounce: 0.4, delay: 0.6}}
              >
                <Link className={filter === "socialmedia" ? "active" : ""} href={"/work?filter=socialmedia"}>Social Media</Link>
              </motion.li>
              <motion.li
              key={"filter3"}
              initial={{y: 50, opacity: 0}}
              animate={{y: 0, opacity: 1}}
              transition={{type: 'spring', bounce: 0.4, delay: 0.7}}
              >
                <Link className={filter === "webdev" ? "active" : ""} href={"/work?filter=webdev"}>Web Development</Link>
              </motion.li>
              <motion.li
              key={"filter4"}
              initial={{y: 50, opacity: 0}}
              animate={{y: 0, opacity: 1}}
              transition={{type: 'spring', bounce: 0.4, delay: 0.8}}
              >
                <Link className={filter === "media" ? "active" : ""} href={"/work?filter=media"}>Media</Link>
              </motion.li>
              <motion.li
              key={"filter5"}
              initial={{y: 50, opacity: 0}}
              animate={{y: 0, opacity: 1}}
              transition={{type: 'spring', bounce: 0.4, delay: 0.9}}
              >
                <Link className={filter === "performance" ? "active" : ""} href={"/work?filter=performance"}>Performance Marketing</Link>
              </motion.li>
            </ul>
         </div>
          <HomeContact />
          <Footer />
        </ScrollContainer>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const res = await fetchClients()
  return { props: { data: res }}
}
