import Background from '@/components/Background'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import ScrollContainer from '@/components/ScrollContainer'
import { fetchClients } from '@/controller/Content'
import HomeContact from '@/sections/Contact'
import Head from 'next/head'
import { useRouter } from 'next/router'
import WorkHero from '@/sections/Work/WorkHero'
import logo from "../../assets/brands/oneplus/oneplus-logo.webp"
import { motion } from 'framer-motion'
import LazyLoad from 'react-lazyload';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  defaults
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import { useState } from 'react'
import SwiperCore, { Pagination, Autoplay } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react'
import 'swiper/css'
import 'swiper/css/pagination'
import 'swiper/css/autoplay'
SwiperCore.use([Autoplay]);
import CountUp from 'react-countup'
import Lottie from 'react-lottie-player/dist/LottiePlayerLight'

import duration from "../../assets/animaticons/duration.json"
import spend from "../../assets/animaticons/spend.json"
import interactions from "../../assets/animaticons/interactions.json"
import followers from "../../assets/animaticons/followers.json"

//camp 3 videos
// import video1 from "../../assets/brands/oneplus/videos/video1.mp4"

//campaign1 pics
import mpic1 from "../../assets/brands/oneplus/mirror/pic1.jpg"
import mpic2 from "../../assets/brands/oneplus/mirror/pic2.jpg"
import mpic3 from "../../assets/brands/oneplus/mirror/pic3.jpg"
import mpic4 from "../../assets/brands/oneplus/mirror/pic4.jpg"
import mpic5 from "../../assets/brands/oneplus/mirror/pic5.jpg"
import mpic6 from "../../assets/brands/oneplus/mirror/pic6.jpg"
import mpic7 from "../../assets/brands/oneplus/mirror/pic7.jpg"
import mpic8 from "../../assets/brands/oneplus/mirror/pic8.jpg"

//campaign2 pics
import cpic1 from "../../assets/brands/oneplus/campaign1/pic1.jpg"
import cpic2 from "../../assets/brands/oneplus/campaign1/pic2.jpg"
import cpic3 from "../../assets/brands/oneplus/campaign1/pic3.jpg"
import cpic4 from "../../assets/brands/oneplus/campaign1/pic4.jpg"
import cpic5 from "../../assets/brands/oneplus/campaign1/pic5.jpg"
import cpic6 from "../../assets/brands/oneplus/campaign1/pic6.jpg"
import cpic7 from "../../assets/brands/oneplus/campaign1/pic7.jpg"


ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

defaults.font.family = 'Matter'
defaults.font.size = 12
defaults.font.weight = 500
defaults.color = "#FFFFFF"

export default function OnePlus() {
  const [xx, setXx] = useState(null)
  const tooltipgen = (tooltipItems) => {
    if(tooltipItems[0]?.label === "2022"){
      return "#8 Sports team in the world"
    }else if(tooltipItems[0]?.label === "2023"){
      return "🎉 #5 Sports team in the world"
    }else{
      return ""
    }
  }
  const options = {
    responsive: true,
    animations: {
      tension: {
        duration: 3000,
        easing: 'ease',
        from: 0.5,
        to: 0.2,
        loop: true
      }
    },
    plugins: {
      legend: {
        display: false,
        position: 'top',
        labels: {
          color: "#FFFFFF",
          font: {
            family: "Matter" // Add your font here to change the font of your legend label
          }
        },
      },
      tooltip: {
        bodyColor: "#FFC64E",
        callbacks: {
          footer: tooltipgen
        }
      }
    },
    scales: {
      y: {
        title: {
          display: true,
          text: 'Interactions (In Millions)',
        },
        grid: {color: '#ffffff10'}
      },
      x: {
        title: {
          display: true,
          text: 'Years'
        },
        grid: {color: '#ffffff10'}
      }
    }
  };
  const labels = ['2020','2021','2022','2023'];

  const data = {
    labels,
    datasets: [
      {
        label: 'Interactions (In Millions)',
        data: [139, 155, 820, 948],
        borderColor: '#A374FF',
        backgroundColor: '#A374FF',
        pointStyle: 'circle',
        pointRadius: 6,
      }
    ],
  };
  const router = useRouter()
  const {filter} = router.query
  return (
    <>
      <Head>
        <title>OkayDone | OnePlus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <Background />
        <Navigation theme={true} />
        <ScrollContainer>
          <div className="brandpage-hero">
            <WorkHero
            brand={"Oneplus"}
            categories={["Influencer Marketing"]}
            back={"/work"}
            logo={logo.src}
            color={"red"} />
          </div>
          <div className="container">
            <div className="brandpage-section-brand">
              <h1>Creative influencer campaign for the most successful smartphone brand in India</h1>
            </div>
            <div className="brandpage-section-campaign">
              <div className="title">
                <h2><span style={{"--spancolor": "#FFC64E"}}>Campaign #1</span><br />OnePlus 7T Pro: Mirror Campaign</h2>
              </div>
              <div className="brandpage-section-campaign-stats">
                <div className="row">
                  <div className="col-3 col-sm-12">
                    <motion.div
                    initial={{y: 100, opacity: 0}}
                    whileInView={{y: 0, opacity: 1}}
                    transition={{type:'spring', bounce: 0.4, delay: 0.1, duration:0.5}}
                    className="counter-box">
                      <div className="counter-box-icon normal">
                      <Lottie
                        animationData={interactions}
                        play
                        style={{ width: 150, height: 100 }}
                      />
                      </div>
                      <div className="counter-box-title">
                        Total Engagement
                      </div>
                      <div className="couter-box-counter">
                        <CountUp className='counter-box-counter-number'
                        formattingFn={(value) => value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                        end={5040321} duration={3} startOnMount={false} />
                      </div>
                    </motion.div>
                  </div>
                  <div className="col-9 col-sm-12">
                    <h2 className='brandpage-section-campaign-stats-head'>Campaign Insights</h2>
                    <ul className="brandpage-section-campaign-stats-list">
                      <li>The campaign represented the idea of the 90Hz refresh rate in the OnePlus 7T Pro through multiple mirror reflections of artists</li>
                      <li>Collaborated with ten celebrities</li>
                    </ul>
                  </div>
                </div>
                <div className="brandpage-section-campaign-slider">
                  <h2>Gallery</h2>
                <Swiper
                  spaceBetween={50}
                  breakpoints={{
                    320: {
                      slidesPerView: 1.5,
                      spaceBetween: 20
                    },
                    480: {
                      slidesPerView: 1,
                      spaceBetween: 30
                    },
                    768: {
                      slidesPerView: 4,
                      spaceBetween: 20
                    },
                  }}
                  modules={[Autoplay, Pagination]}
                  loop={true}
                  loopedSlides={3}
                  direction={"horizontal"}
                  autoplay={{
                    delay: 2000,
                    disableOnInteraction: false,
                  }}
                  pagination={{ clickable: true}}
                  onSlideChange={() => console.log('slide change')}
                  onSwiper={(swiper) => console.log(swiper)}
                >
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic1.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic2.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic3.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic4.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic5.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic6.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic7.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={mpic8.src} alt="" />
                  </SwiperSlide>
                </Swiper>
               </div>
              </div>
            </div>
            <div className="brandpage-section-campaign">
              <div className="title">
                <h2><span style={{"--spancolor": "#FFC64E"}}>Campaign #2</span><br />Oneplus 7T Pro McLaren Edition</h2>
              </div>
              <div className="brandpage-section-campaign-stats">
                <div className="row">
                  <div className="col-3 col-sm-12">
                    <motion.div
                    initial={{y: 100, opacity: 0}}
                    whileInView={{y: 0, opacity: 1}}
                    transition={{type:'spring', bounce: 0.4, delay: 0.1, duration:0.5}}
                    className="counter-box">
                      <div className="counter-box-icon normal">
                      <Lottie
                        animationData={interactions}
                        play
                        style={{ width: 150, height: 100 }}
                      />
                      </div>
                      <div className="counter-box-title">
                        Total Engagement
                      </div>
                      <div className="couter-box-counter">
                        <CountUp className='counter-box-counter-number'
                        formattingFn={(value) => value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                        end={5041385} duration={3} startOnMount={false} />
                      </div>
                    </motion.div>
                  </div>
                  <div className="col-9 col-sm-12">
                    <h2 className='brandpage-section-campaign-stats-head'>Campaign Insights</h2>
                    <ul className="brandpage-section-campaign-stats-list">
                      <li>The campaign captures the alter ego of individuals to represent the new avatar of OnePlus’s Limited Edition: 7T PRO!</li>
                      <li>Collaborated with eight celebrities</li>
                    </ul>
                  </div>
                </div>
                <div className="brandpage-section-campaign-slider">
                  <h2>Gallery</h2>
                <Swiper
                  spaceBetween={50}
                  breakpoints={{
                    320: {
                      slidesPerView: 1.5,
                      spaceBetween: 20
                    },
                    480: {
                      slidesPerView: 1,
                      spaceBetween: 30
                    },
                    768: {
                      slidesPerView: 4,
                      spaceBetween: 20
                    },
                  }}
                  modules={[Autoplay, Pagination]}
                  loop={true}
                  loopedSlides={3}
                  direction={"horizontal"}
                  autoplay={{
                    delay: 2000,
                    disableOnInteraction: false,
                  }}
                  pagination={{ clickable: true}}
                  onSlideChange={() => console.log('slide change')}
                  onSwiper={(swiper) => console.log(swiper)}
                >
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic1.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic2.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic3.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic4.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic5.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic6.src} alt="" />
                  </SwiperSlide>
                  <SwiperSlide className="brandpage-section-campaign-slider-slide">
                    <img src={cpic7.src} alt="" />
                  </SwiperSlide>
                </Swiper>
               </div>
              </div>
            </div>
            <div className="brandpage-section-campaign">
              <div className="title">
                <h2><span style={{"--spancolor": "#FFC64E"}}>Campaign #3</span><br />#Yourfestiveshot (Diwali campaign)</h2>
              </div>
              <div className="brandpage-section-campaign-stats">
                <div className="row">
                  <div className="col-3 col-sm-12">
                    <motion.div
                    initial={{y: 100, opacity: 0}}
                    whileInView={{y: 0, opacity: 1}}
                    transition={{type:'spring', bounce: 0.4, delay: 0.1, duration:0.5}}
                    className="counter-box">
                      <div className="counter-box-icon">
                      <Lottie
                        animationData={duration}
                        play
                        style={{ width: 150, height: 100 }}
                      />
                      </div>
                      <div className="counter-box-title">
                        Duration
                      </div>
                      <div className="couter-box-counter">
                        <CountUp className='counter-box-counter-number'
                        suffix=' DAYS'
                        end={10} duration={3} startOnMount={false} />
                      </div>
                    </motion.div>
                  </div>
                  <div className="col-9 col-sm-12">
                    <h2 className='brandpage-section-campaign-stats-head'>Milestones</h2>
                    <ul className="brandpage-section-campaign-stats-list">
                      <li>250+ entries received during the campaign period</li>
                      <li>Collaborated with 75+ photographers, influencers, & travelers for #YourFestiveShot campaign</li>
                      <li>OnePlus’s most successful O2O campaign</li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="brandpage-section-campaign-videos">
                <div className="row">
                  <div className="col-6 col-sm-12">
                    <LazyLoad height={200}>
                      <video className='brandpage-section-campaign-videos-video left' controls>
                        <source src="/videos/video1.mp4" type="video/mp4" />
                        Your browser does not support the video tag.
                      </video>
                    </LazyLoad>
                  </div>
                  <div className="col-6 col-sm-12">
                    <LazyLoad height={200}>
                      <video className='brandpage-section-campaign-videos-video right' controls>
                        <source src="/videos/video2.mp4" type="video/mp4" />
                        Your browser does not support the video tag.
                      </video>
                    </LazyLoad>
                  </div>
                  <div className="col-6 col-sm-12">
                    
                  </div>
                </div>
              </div>
            </div>
            <div className="brandpage-section-content notop">
              <div className="title">
                <h2>Campaign Insights</h2>
              </div>
              <div className="subtitle">
                <ul>
                  <motion.li
                  key={`rcb-subtitle-miles1`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.2}}
                  >As celebrations and festivities double up when shared with others, <span>#Yourfestiveshot</span>  gave users a chance to feature their festive Diwali photographs on OnePlus billboards around the country!</motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles2`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.3}}
                  >The images on the billboard kept changing in real time, as more and more people uploaded their festive shots on social media using the hashtag <span>#YourFestiveShot</span></motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles3`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.4}}
                  >The festive shots were displayed on billboards across Bangalore, Mumbai, Pune, Kolkata, Hyderabad, Delhi, Jaipur, and Ahmedabad, illuminating the night sky with beautiful moments shot on OnePlus.</motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles4`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.5}}
                  >Diwali 2021 was about things looking up after a long time. The OOH campaign captured this thought beautifully, making people look up quite literally!</motion.li>
                </ul>
              </div>
            </div>
          </div>
          <Footer />
        </ScrollContainer>
      </main>
    </>
  )
}
