import Background from '@/components/Background'
import Footer from '@/components/Footer'
import Navigation from '@/components/Navigation'
import ScrollContainer from '@/components/ScrollContainer'
import { fetchClients } from '@/controller/Content'
import HomeContact from '@/sections/Contact'
import Head from 'next/head'
import { useRouter } from 'next/router'
import WorkHero from '@/sections/Work/WorkHero'
import logo from "../../assets/brands/rcb/royal-challengers-bangalore.png"
import { motion } from 'framer-motion'

export default function RCB({data}) {
  const router = useRouter()
  const {filter} = router.query
  return (
    <>
      <Head>
        <title>OkayDone | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"main"}>
        <Background />
        <Navigation theme={true} />
        <ScrollContainer>
          <div className="brandpage-hero">
            <WorkHero
            title={"Empowering an epic fan moment through powerful social media showmanship"}
            brand={"Royal Challengers Banglore"}
            categories={["Social Media", "Performance Marketing"]}
            color={"purple"} />
          </div>
          <div className="container">
            <div className="brandpage-section-brand">
              <div className="logo">
                <img src={logo.src} alt="" />
              </div>
              <h1>Royal Challengers Banglore</h1>
            </div>
            <div className="brandpage-section-content">
              <div className="title">
                <h2>Recent Milestones</h2>
              </div>
              <div className="subtitle">
                <ul>
                  <motion.li
                  key={`rcb-subtitle-miles1`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.2}}
                  >The most popular cricket team team in the world ranked by interactions on <strong>Instagram during 2022: 948M Impressions</strong></motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles2`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.3}}
                  ><strong>The 5th most popular sports team in the world</strong> ranked by total interactions during 2022</motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles3`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.4}}
                  >Most popular Cricket team in Asia</motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles4`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.5}}
                  >Most Popular Cricket team in the World</motion.li>
                  <motion.li
                  key={`rcb-subtitle-miles5`}
                  initial={{x: 150, opacity: 0}}
                  whileInView={{x: 0, opacity: 1}}
                  transition={{duration: 0.5, bounce: 0.4, type: 'spring', delay: 0.6}}
                  >Most Popular Sports team in Asia</motion.li>
                </ul>
              </div>
            </div>
          </div>
          <HomeContact />
          <Footer />
        </ScrollContainer>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const res = await fetchClients()
  return { props: { data: res }}
}
